fq_in_path: "data/fastq"
trim_out_path: "data/trimmed"



maskRegion: "ref/mm9-blacklist.bed.gz"
lam_ref: "ref/lam_mc.fa"
lam_bed: "ref/lam_mc.bed"
ref_genome: "ref/bowtie2/spike"
ref_fa: "/home/index/wangzc/cgs/new_mm9_lam_mc.fa"
chrs.bed: "ref/chrs.bed"
get_pair300_py: "ref/get_pre_300.py"
get_split_py: "ref/get_split.py"
get_pair_py: "ref/get_pair.py"


CHRs: ["chr1","chr2","chr3","chr4","chr5","chr6","chr7","chr8","chr9","chr10","chr11","chr12","chr13","chr14","chr15","chr16","chr17","chr18","chr19","chrX","chrY"]
MAPQ: "10"

sampleList: ["Caps_PCR"]
